### ISSUE TITLE
Map View Resizing

### ISSUE THREAD

**Issue by vinikkk** [NinevaStudios/unity-google-maps-docs#6]
Hey, I would like to resize the map view on the fly, there is any way to do that?

Thanks in advance :)

**Comment by TarasOsiris** [comment]
Hello, please use `SetRect()` method on map view

**Comment by TarasOsiris** [comment]
#5 Duplicate

**Comment by vinikkk** [comment]
Hey, sorry for my newbieness, but I did not found this function on the GoogleMapsView object... :(

So, I have this guy already working like a charm:
public static DeadMosquito.GoogleMapsView.GoogleMapsView map;

but I need to resize it in the Y axis. And it appears to me that the SetRect method would do it but there is none :(

**Comment by TarasOsiris** [comment]
Please see the example in `GoogleMapsDemo.cs` example scrip inside the package

```csharp
[UsedImplicitly]
public void OnSetMapPosition()
{
    if (_map != null)
    {
        _map.SetRect(new Rect(0f, 0f, _screenWidth / 2f, _screenHeight / 2f));
    }
}
```
