### ISSUE TITLE
Map Not loading in IOS

### ISSUE THREAD

**Issue by avinash018** [NinevaStudios/unity-google-maps-docs#7]
Hello,
         Map is loading in Android but not in IOS. I have seen the markers, location Button & location pointer loading properly. But the map is not loading. Please tell me what to do.

Thanks,
Avinash

**Comment by TarasOsiris** [comment]
Hello,

If the maps is not loading on iOS please make sure you followed the setup for iOS carefully: https://github.com/NinevaStudios/unity-google-maps-docs/wiki/Setup-(iOS)

If the map doesn't load it means you have missed some step, I suggest to go through setup and re-check everything carefully
